// Top-level build.gradle — applied to all modules.
buildscript {
    ext {
        kotlin_version = '1.9.24'
        compose_version = '1.6.10'
        hilt_version = '2.51'
        room_version = '2.6.1'
        agp_version = '8.3.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory.get().asFile
}
